### ISSUE TITLE
EFH: Fehler in der Anzeige im Kommentarfeld

### ISSUE THREAD

**Issue by brigittegraef** [epigraphic-database-heidelberg/website#101]
Beispiel F016318:

"="-Zeichen wird auf der Homepage "&#61;" angezeigt. S. auch Screenshot.
![EFH_Kommentarfeld](https://user-images.githubusercontent.com/56920358/108207491-1a5f0f00-7128-11eb-8b05-91a2186157d2.JPG)

**Comment by wenamun** [comment]
erl.
