### ISSUE TITLE
Geo-Db: Generalbefehl im Feld "Pleiades-IDs"

### ISSUE THREAD

**Issue by brigittegraef** [epigraphic-database-heidelberg/website#92]
In allen Datensätze mit Fundort modern = 'Lyon" (NICHT: "Lyons-la-Forêt")
die Pleiades-ID ändern in
"167717"
(= 65 Datensätze).

Im Moment steht dort die Pleiades-ID 99003, die auf ein anderes Lugdunum in den Niederlanden weist. Dadurch sind alle Marker auch automatisiert in den Niederlanden gelandet. Kann man die Marker für diese Datensätze automatisiert ins französische Lyon verschieben?

**Comment by wenamun** [comment]
erl.
